name: ci-dbadger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true

    - name: Build
      run: |
        go mod download
        go build -v ./cmd/...

    - name: Test
      run: make test

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        make cover
        go install github.com/mattn/goveralls@latest
        goveralls -coverprofile=coverage.txt -repotoken=$COVERALLS_TOKEN
